- build.gradle
- lombok.config
- src/main/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersController.java
- src/main/java/uk/gov/hmcts/reform/cpo/controllers/RootController.java
- src/main/java/uk/gov/hmcts/reform/cpo/data/CasePaymentOrderEntity.java
- src/main/java/uk/gov/hmcts/reform/cpo/domain/CasePaymentOrder.java
- src/main/java/uk/gov/hmcts/reform/cpo/repository/CasePaymentOrdersRepository.java
- src/main/java/uk/gov/hmcts/reform/cpo/service/CasePaymentOrdersService.java
- src/main/java/uk/gov/hmcts/reform/cpo/service/impl/CasePaymentOrdersServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cpo/service/mapper/CasePaymentOrderMapper.java
- src/test/java/uk/gov/hmcts/reform/cpo/service/CasePaymentOrdersServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cpo/service/mapper/CasePaymentOrderMapperTest.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/DemoUnitTest.java
Reverts hmcts/cpo-case-payment-orders-api#6
> Revert "Temporarily - Revert "CPO-12: Set up skeleton classes and initial entities and domain classes""

- src/main/java/uk/gov/hmcts/reform/cpo/config/SwaggerConfiguration.java
> swagger typo fixes

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/cpo/BaseTest.java
- src/integrationTest/resources/application-itest.yaml
- src/integrationTest/resources/integration-test.properties
- src/main/java/uk/gov/hmcts/reform/cpo/Application.java
- src/main/resources/application.yaml
> Add in testcontainers for postgres

- build.gradle
> Update some dependencies

- Dockerfile
- build.gradle
- charts/cpo-case-payment-orders-api/Chart.yaml
- charts/cpo-case-payment-orders-api/values.yaml
- src/main/resources/application.yaml
Minor tweaks
1. key-vault setting for AppInsightsInstrumentationKey 
2. [Spring boot layered jars ](https://www.baeldung.com/spring-boot-docker-images#3-creating-the-docker-image)
3. dependency cleanup
> Minor tweaks

- charts/cpo-case-payment-orders-api/Chart.yaml
- charts/cpo-case-payment-orders-api/values.yaml
> correcting vault secret name

- infrastructure/main.tf
> modified resource group name

- src/main/java/uk/gov/hmcts/reform/cpo/data/CasePaymentOrderEntity.java
- src/main/java/uk/gov/hmcts/reform/cpo/domain/CasePaymentOrder.java
- src/main/resources/db/migration/V20210331_21__CPO-21-RemoveCaseTypeId.sql
- src/test/java/uk/gov/hmcts/reform/cpo/service/mapper/CasePaymentOrderMapperTest.java
added new DB migration file V20210331_21__CPO-21-RemoveCaseTypeId.sql to remove case type id
removed all references to case type id
```
[ ] Yes
[ ] No
```
> CPO-21 Remove Case Type ID

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersController.java
- src/main/java/uk/gov/hmcts/reform/cpo/data/CasePaymentOrderEntity.java
- src/main/java/uk/gov/hmcts/reform/cpo/exception/HttpError.java
- src/main/java/uk/gov/hmcts/reform/cpo/repository/CasePaymentOrderQueryFilter.java
- src/main/java/uk/gov/hmcts/reform/cpo/repository/CasePaymentOrdersRepository.java
- src/main/java/uk/gov/hmcts/reform/cpo/service/impl/CasePaymentOrdersServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cpo/validators/CaseIdsValidator.java
- src/main/java/uk/gov/hmcts/reform/cpo/validators/IdsValidator.java
- src/test/java/uk/gov/hmcts/reform/cpo/service/CasePaymentOrdersServiceImplTest.java
DAN DAN sorry for breaking the build !
> caseTypeId  removed

- .github/workflows/dummy.yml
> dummy commit cron

- src/main/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersController.java
- src/main/java/uk/gov/hmcts/reform/cpo/payload/CreateCasePaymentOrderRequest.java
> Swagger updates

- src/test/java/uk/gov/hmcts/reform/BaseTest.java
- src/test/java/uk/gov/hmcts/reform/cpo/service/CasePaymentOrdersServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cpo/validators/CaseIdsTest.java
- src/test/java/uk/gov/hmcts/reform/cpo/validators/IdsTest.java
>  CPO-7: Build GetPaymentOrders endpoint

- charts/cpo-case-payment-orders-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-808?filter=-1
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```
> CCD-808 Upgrade Base Chart Versions (Java & Nodejs)

- Jenkinsfile_CNP
> Jenkins befta env cleanup and redirect_uri fix

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1566
```
[ ] Yes
[x] No
```
> suppress CVE

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1644
https://tools.hmcts.net/jira/browse/CCD-1647
fix for CVE-2021-30639
```
[ ] Yes
[x] No
```
> fix for CVE-2021-30639

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1576
Integrated Fortify Scan into Nightly Pipelines
```
[ ] Yes
[x] No
```
> CCD-1576: Integrate Fortify Scan into Nightly Pipelines

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersControllerIT.java
https://tools.hmcts.net/jira/browse/CCD-1653
https://tools.hmcts.net/jira/browse/CCD-1654
fix for Fortify Issue 14727908-14727909  Null Dereference
```
[ ] Yes
[ ] No
```
> fix for Fortify Issue 14727908-14727909  Null Dereference

- build.gradle
- config/owasp/suppressions.xml
Resolve CVE-2021-22119 & CVE-2021-28170
```
[ ] Yes
[x] No
```
> Resolve CVE-2021-22119 & CVE-2021-28170

- src/functionalTest/resources/features/F-701 - createCasePaymentOrder/S-701.2.2.td.json
- src/functionalTest/resources/features/F-701 - createCasePaymentOrder/S-701.2.4.td.json
- src/functionalTest/resources/features/F-701 - createCasePaymentOrder/S-701.2.5.td.json
- src/functionalTest/resources/features/F-703 - getCasePaymentOrder/S-703.1.td.json
- src/functionalTest/resources/features/F-703 - getCasePaymentOrder/S-703.2.td.json
- src/functionalTest/resources/features/F-703 - getCasePaymentOrder/S-703.7.td.json
- src/functionalTest/resources/features/F-705/common/Base_Case_Payment_Order.td.json
- src/functionalTest/resources/features/common/Base_CPO_Payload_Data.td.json
- src/functionalTest/resources/features/common/Base_CPO_Update_Payload_Data.td.json
- src/functionalTest/resources/features/common/Prerequisite_Create_CPO_2.td.json
- src/functionalTest/resources/features/common/Prerequisite_Create_CPO_3.td.json
- src/functionalTest/resources/features/common/response/Base_CPO_Response_Data.td.json
- src/integrationTest/java/uk/gov/hmcts/reform/cpo/BaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cpo/utils/CasePaymentOrderEntityGenerator.java
- src/main/java/uk/gov/hmcts/reform/cpo/payload/BaseCasePaymentOrderRequest.java
- src/main/java/uk/gov/hmcts/reform/cpo/validators/Validator.java
- src/test/java/uk/gov/hmcts/reform/BaseTest.java
- src/test/java/uk/gov/hmcts/reform/cpo/controllers/CasePaymentOrdersControllerTest.java
https://tools.hmcts.net/jira/browse/CPO-60
Increase order_reference validation from 16 to 18 characters
```
[ ] Yes
[X] No
```
> CPO-60: Increase order_reference validation from 16 to 18 characters

- config/owasp/suppressions.xml
CCD-2107 (https://tools.hmcts.net/jira/browse/CCD-2107)
Updated CVE suppression dates in suppressions.xml to 25/12/2021
```
[ ] Yes
[x] No
```
> CCD-2107: Update CVE suppression dates

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Amending suppression dates by 1 month
```
[ ] Yes
[X ] No
```
> Amending suppression dates by 1 month

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```
> Update to build.gradle

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2591
Suppressing:
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832
```
[ ] Yes
[ x] No
```
> CCD-2591: Suppress CVE pending investigation

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2696
CWE-862 Suppression
```
[ ] Yes
[X ] No
```
> CWE-862 Suppression

- charts/cpo-case-payment-orders-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> update helm version

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2718
```
[ ] Yes
[ ] No
```
> test definition version update to 7.13.0

- charts/cpo-case-payment-orders-api/Chart.yaml
> Upgrade to Latest Base Helm Charts

- charts/cpo-case-payment-orders-api/Chart.yaml
- charts/cpo-case-payment-orders-api/values.yaml
https://tools.hmcts.net/jira/browse/CCD-2763
Granted create access
```
[ ] Yes
[x] No
```
> CCD-2763: Allowed-listing service_request_cpo_update_service for accessing CPO API

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2923
CVE-2022-22965
```
[ ] Yes
[X ] No
```
> Bump Spring framework to 5.3.18

- config/owasp/suppressions.xml
Suppression for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[ x] No
```
> spring-core-5.3.18.jar dependency suppression

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2696
Fix for jackson dependency issue to heal master pipeline.
```
[ ] Yes
[x] No
```
> Hotfix for jackson dependency issue

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3110
```
[ ] Yes
[x] No
```
> package update for CVE-2022-21724

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3293
Removed suppressions and updated spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```
> CCD-3293: Removed suppressions and updated spring-framework.version to 5.3.20

- charts/cpo-case-payment-orders-api/Chart.yaml
- config/owasp/suppressions.xml
n/a
Add comment to suppressions.xml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Add comment to suppressions.xml

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3433
Update suppressions.xml added temporary suppression for CVE-2022-34305
```
[ ] Yes
[X] No
```
> Update suppressions.xml added temporary suppression for CVE-2022-34305

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3450
CCD-3450 : Update suppressions.xml (CVE-2022-33915)
```
[ ] Yes
[X] No
```
> CCD-3450 : Update suppressions.xml (CVE-2022-33915)

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3450
False positive.   CVE-2022-33915 (cpe;2.3;a;apache;log4j) only impacts AWS Log4j hotpatch , and not general Log4j build.   See Jira ticket.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> CCD-3450: CVE-2022-33915 cpo-case-payment-orders-api

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-965
CCD-965: Remove Temporary Sonar Exclusions cpo-case-payment-orders-api
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> CCD-965: Remove Temporary Sonar Exclusions cpo-case-payment-orders-api

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3512
Fixed
```
[ ] Yes
[x] No
```
> CCD-3512: Fix for CVE-2022-22969

- config/owasp/suppressions.xml
CCD-3607 (https://tools.hmcts.net/jira/browse/CCD-3607)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```
> CCD-3607: Temporarily suppress CVE-2022-31197

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[x ] No
```
> Ccd 3577 cleanup CVE suppressions

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-3563
Remove Version Number
```
[ ] Yes
[ X] No
```
> Remove Version Number

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4047
Upgraded 'org.postgresql' to version: '42.5.1'
```
[ ] Yes
[X] No
```
> CCD-4047-Fix-CVE-2022-41946

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4163
https://tools.hmcts.net/jira/browse/CCD-4086
Bump rse-gradle-java-plugin to 0.12.37
Remove CVE-2021-37533
```
[ ] Yes
[X] No
```
> CCD-4163 Bump rse-gradle-java-plugin

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4313
CVE cleanup.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> CCD-4313: CVE cleanup

- charts/cpo-case-payment-orders-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
> Ccd 4317 upgrade base charts

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4479
https://tools.hmcts.net/jira/browse/CCD-4509
upgrade Spring Framework version to 5.3.26 for CVE-2023-20861 
Fix for CVE-2023-20860
```
[ ] Yes
[ ] No
```
> CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CCD-4479
replace .internal url
```
[ ] Yes
[X] No
```
> CCD-4479 : Update Jenkinsfile_CNP

- .github/renovate.json
> CCD-4608 Update renovate.json

- .github/renovate.json
- Jenkinsfile_CNP
- build.gradle
- lib/applicationinsights.json
> CCD-3710 AppInsights Health Sampling/fix build

- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/HMAN-602
Add retries to manifest-create
```
[ ] Yes
[ x] No
```
> HMAN-602 : Add retries to manifest-create

- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/HMAN-602
Remove keep step in acb entries to fix retry issue
```
[ ] Yes
[ x] No
```
> Remove keep step in acb entries

- Dockerfile
- build.gradle
- charts/cpo-case-payment-orders-api/values.preview.template.yaml
- lib/applicationinsights.json
- src/main/resources/application.yaml
Attempt to fix ApplicationInsights
https://tools.hmcts.net/jira/browse/CCD-5150
```
[ ] Yes
[ x] No
```
> Attempt to fix ApplicationInsights

- config/owasp/suppressions.xml
[CCD-5024](https://tools.hmcts.net/jira/browse/CCD-5024)
Removed suppression
```
[ ] Yes
[X] No
```
> CCD-5024 Update suppressions.xml

- infrastructure/main.tf
> Retrigger DB v15 user script

- infrastructure/main.tf
> Re-run DB permissions script following user creation

- infrastructure/state.tf
> Update state.tf fix TF build

- infrastructure/state.tf
> Update state.tf fix build

- build.gradle
> fix fortify gradle tax

- infrastructure/output.tf
- infrastructure/state.tf
- infrastructure/variables.tf
> Fix master

- README.md
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5518
bumped postgresql to 42.6.1
```
[ ] Yes
[X] No
```
> CCD-5518 : Fix-CVE-2024-1597

- build.gradle
- config/owasp/suppressions.xml
https://github.com/hmcts/cpo-case-payment-orders-api/pull/294/files
```
[ ] Yes
[ ] No
```
> Revert ccd 5159

- infrastructure/main.tf
- infrastructure/state.tf
NA
Fix master pipeline 
```
[ ] Yes
[X] No
```
> Fix master tf

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5953
removed suppression
```
[ ] Yes
[X] No
```
> CCD-5953 : Fix-CVE-2023-52428

- .github/workflows/swagger.yml
https://tools.hmcts.net/jira/browse/CME-69
```
[ ] Yes
[ ] No
```
> CME-69: add java distro to workflow

- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-316
Standardise version
```
[ ] Yes
[ x] No
```
> CME-316: Update azurerm

- befta_recent_executions_info_UnspecifiedEnvironment.json
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/cpo/befta/CasePaymentOrdersBeftaRunner.java
https://tools.hmcts.net/jira/browse/CCD-6049
CCD-6049 : Bump ccd-test-definitions and befta-fw to latest
```
[ ] Yes
[X] No
```
> CCD-6049 : Bump ccd-test-definitions and befta-fw to latest

- config/owasp/suppressions.xml
> remove redundant cves

- charts/cpo-case-payment-orders-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
> CCD-6193 update Base Chart Version

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6353
```
[ ] Yes
[ ] No
```
> cve_supression_cpo_case-payemnt

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6389
```
[ ] Yes
[ ] No
```
> CCD-6389 tidy up

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6489
CCD-6489 :: suppress CVE 2024 22259
```
[ ] Yes
[X] No
```
> CCD-6489 :: suppress CVE 2024 22259
